#!/usr/bin/env bash

export DESKTOP_SESSION=HyprDrift
export HYPRLAND_INSTANCE_SIGNATURE=$(uuidgen)
systemctl --user import-environment DESKTOP_SESSION

# Optionally help with Wayland compatibility
export QT_QPA_PLATFORM=wayland
export GDK_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland

# Start background services
while [ -z "$XDG_RUNTIME_DIR" ]; do
    sleep 0.1
done

# If ~/.config/hypr/conf doesn't exist, copy default config
if [ ! -d "$HOME/.config/hypr/conf" ]; then
    echo "[+] No user Hypr config found. Copying defaults from /etc/hyprdrift/hypr/"
    mkdir -p "$HOME/.config"
    cp -r /etc/hyprdrift/hypr "$HOME/.config/"
fi

/usr/bin/drift-daemon &
systemctl --user start quickdrift.service

# Start Hyprland in foreground
exec Hyprland
