general:
  timeFormat: hh:mm:ap
  dateFormat: ddd/dd/mm/yyyy
  logLocation: $HOME/.cache/hyprdrift/logs/drift
  userConfigFile: $HOME/.config/hyprdrift/config/drift-config.yaml
  defaultConfigFile: /etc/hyprdrift/config/drift-config.yaml
  startupApps:
    - firefox.desktop

theme:
  base: catppuccin-frappe         # base16/tinted name
  variant: dark                   # UI hint
  accentColor: "#89b4fa"          # Custom accent if overriding
  borderRadius: 6                 # Rounded corner radius in px
  panelOpacity: 0.85              # UI visuals
  font:
    family: "JetBrainsMono Nerd Font"
    size: 11

interface:
  panel:
    enabled: true
    position: top
    floating: true
    width:
      mode: fill
    height:
      mode: fit
    leftModules:
      - launcherButton
    centerModules:
      - windowTitle
    rightModules:
      - cpu
      - bluetooth
      - network
      - tray
      - powerButton
      - clock
  dock:
    enabled: true
    position: left
    floating: true
    height: fit
    width: 30

shortcuts:
  launcher: "Super+Space"
  terminal: "CTRL+`"



core:
  coreLocation: /usr/bin/drift-daemon
  debugMode: false